[email]
sender = "SomeSenderName <sender@domain.dom>"
recipients = ["SomeRecipient1 <some@recipient1.dom>", "SomeRecipient2 <some@recipient2.dom>"]
smtp_host = "some.smtp.host.dom"
smtp_username = "some-smtp-username"
smtp_password = "some-smtp-pass"

[[products]]
url = "https://some-store.dom/some-prod1.html"
selector = "div.some-class"
use_selector_attr = "content"

[[products]]
url = "https://some-store.dom/some-prod2.html"
selector = "span.a-price>span.a-price-content"
